import React from "react";
import JobList from "../jobs/_components/JobList";

export default function JobsPage() {
  //create sample job data based on this         jobTitle="Software Engineer"

  const jobPosts = [
    {
      jobTitle: "Software Engineer1",
      companyName: "Tech Company",
      location: "New York, NY",
      salary: "$100,000 - $120,000",
      applicants: 10,
      createdAt: "2023-10-01",
      status: "Open",
      id: "1",
    },
    {
      jobTitle: "Product Manager2",
      companyName: "Innovative Solutions",
      location: "San Francisco, CA",
      salary: "$120,000 - $140,000",
      applicants: 5,
      createdAt: "2023-10-02",
      status: "Open",
      id: "2",
    },
    {
      jobTitle: "Software Engineer3",
      companyName: "Tech Company",
      location: "New York, NY",
      salary: "$100,000 - $120,000",
      applicants: 10,
      createdAt: "2023-10-01",
      status: "Open",
      id: "3",
    },
    {
      jobTitle: "Product Manager4",
      companyName: "Innovative Solutions",
      location: "San Francisco, CA",
      salary: "$120,000 - $140,000",
      applicants: 5,
      createdAt: "2023-10-02",
      status: "Open",
      id: "4",
    },
    {
      jobTitle: "Software Engineer5",
      companyName: "Tech Company",
      location: "New York, NY",
      salary: "$100,000 - $120,000",
      applicants: 10,
      createdAt: "2023-10-01",
      status: "Open",
      id: "5",
    },
    {
      jobTitle: "Product Manager6",
      companyName: "Innovative Solutions",
      location: "San Francisco, CA",
      salary: "$120,000 - $140,000",
      applicants: 5,
      createdAt: "2023-10-02",
      status: "Open",
      id: "6",
    },
    {
      jobTitle: "Software Engineer7",
      companyName: "Tech Company",
      location: "New York, NY",
      salary: "$100,000 - $120,000",
      applicants: 10,
      createdAt: "2023-10-01",
      status: "Open",
      id: "7",
    },
    {
      jobTitle: "Product Manager8",
      companyName: "Innovative Solutions",
      location: "San Francisco, CA",
      salary: "$120,000 - $140,000",
      applicants: 5,
      createdAt: "2023-10-02",
      status: "Open",
      id: "8",
    },
    {
      jobTitle: "Product Manager9",
      companyName: "Innovative Solutions",
      location: "San Francisco, CA",
      salary: "$120,000 - $140,000",
      applicants: 5,
      createdAt: "2023-10-02",
      status: "Open",
      id: "9",
    },
    {
      jobTitle: "Product Manager10",
      companyName: "Innovative Solutions",
      location: "San Francisco, CA",
      salary: "$120,000 - $140,000",
      applicants: 5,
      createdAt: "2023-10-02",
      status: "Open",
      id: "10",
    },
    {
      jobTitle: "Product Manager11",
      companyName: "Innovative Solutions",
      location: "San Francisco, CA",
      salary: "$120,000 - $140,000",
      applicants: 5,
      createdAt: "2023-10-02",
      status: "Open",
      id: "11",
    },
    {
      jobTitle: "Product Manager12",
      companyName: "Innovative Solutions",
      location: "San Francisco, CA",
      salary: "$120,000 - $140,000",
      applicants: 5,
      createdAt: "2023-10-02",
      status: "Open",
      id: "12",
    },
    {
      jobTitle: "Product Manager13",
      companyName: "Innovative Solutions",
      location: "San Francisco, CA",
      salary: "$120,000 - $140,000",
      applicants: 5,
      createdAt: "2023-10-02",
      status: "Open",
      id: "13",
    },
    {
      jobTitle: "Product Manager14",
      companyName: "Innovative Solutions",
      location: "San Francisco, CA",
      salary: "$120,000 - $140,000",
      applicants: 5,
      createdAt: "2023-10-02",
      status: "Open",
      id: "14",
    },
    {
      jobTitle: "Product Manager15",
      companyName: "Innovative Solutions",
      location: "San Francisco, CA",
      salary: "$120,000 - $140,000",
      applicants: 5,
      createdAt: "2023-10-02",
      status: "Open",
      id: "15",
    },
    {
      jobTitle: "Product Manager16",
      companyName: "Innovative Solutions",
      location: "San Francisco, CA",
      salary: "$120,000 - $140,000",
      applicants: 5,
      createdAt: "2023-10-02",
      status: "Open",
      id: "16",
    },
    {
      jobTitle: "Product Manager17",
      companyName: "Innovative Solutions",
      location: "San Francisco, CA",
      salary: "$120,000 - $140,000",
      applicants: 5,
      createdAt: "2023-10-02",
      status: "Open",
      id: "17",
    },
    {
      jobTitle: "Product Manager18",
      companyName: "Innovative Solutions",
      location: "San Francisco, CA",
      salary: "$120,000 - $140,000",
      applicants: 5,
      createdAt: "2023-10-02",
      status: "Open",
      id: "18",
    },
    // Add more job posts as needed
  ];

  return (
    <div className="p-4">
      <h1 className="text-2xl font-bold mb-4">All Bookmarked Jobs</h1>
      <JobList jobPosts={jobPosts} />
    </div>
  );
}
